name: Automatic testing
runs-on: workflow_dispatch

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
        
      - name: Do something
        run: echo "hi!"
