name: Automatic testing
on: workflow_dispatch

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Install stuff
        run: pip install -e .[dev]       
 
      - name: Do something
        run: echo "hi!"
