name: Automatic testing
on: workflow_dispatch

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
#      - name: Install stuff
#        run: pip install -e .[dev]       
 
      - name: Do something
        run: echo "hi!"
